# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Cohort component population projection (C++ implementation)
#'
#' The cohort component method of population projection (CCMPP) is a
#' deterministic method for projecting age-stratified population
#' counts forward in time, accounting for births, deaths, and net
#' migration. It is described in \cite{Preston, et al., (2001)},
#' Chapter 6, and many other places. 
#'
#' This implementation is written in C++ and projects the baseline
#' population forward once \code{step_size} years.
#'
#' @author
#' Mark Wheldon, Sara Hertog
#' 
#' @references
#' Preston, S. H., Heuveline, P., and Guillot, M. (2001), \emph{Demography: Measuring and Modeling Population Processes}, Malden, Massachusetts: Blackwell.
#' @export
project_ccmpp <- function(step_size, P0M, P0F, SxM, SxF, asfr, NMxM, NMxF, srb = 1.05, migration_assumption = 1L) {
    .Call(`_ccmppWPP_project_ccmpp`, step_size, P0M, P0F, SxM, SxF, asfr, NMxM, NMxF, srb, migration_assumption)
}

